# msg for referee system
bool supply_1_occupation # 己方补给站 1 号补血点占领状态 1 为已占领
bool supply_2_occupation # 己方补给站 2 号补血点占领状态 1 为已占领
bool rune_hit_occupation # 己方能量机关状态 打击点占领状态, 1 为占领
bool rune_small_enable # 己方能量机关状态 小能量机关激活状态, 1 为已激活
bool rune_big_enable # 己方能量机关状态 大能量机关激活状态, 1 为已激活
bool highland_2_occupation # 己方侧 R2/B2 环形高地占领状态 1 为已占领
bool highland_3_occupation # 己方侧 R3/B3 梯形高地占领状态 1 为已占领
bool highland_4_occupation # 己方侧 R4/B4 梯形高地占领状态 1 为已占领
bool base_shield_enable # 己方基地护盾状态 1 为基地有虚拟护盾血量 0 为基地无虚拟护盾血量
bool base_front_remain # 己方前哨战状态 1 为前哨战存活 0 为前哨战被击毁